apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cydb-submissions
spec:
  host: "{{ .Values.route.name }}"
  to:
    kind: Service
    name: cydb-submissions
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
