apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cydb-submissions-search
  labels:
    app: cydb-submissions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
